# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=768m

# Fabric Properties
minecraft_version=1.18.2
supported_minecraft_versions=1.18.2
loader_version=0.14.25
yarn_mappings=1.18.2+build.4

# Fabric API
fabric_api_version=0.77.0+1.18.2

# Mod Properties
mod_version=1.0.2
maven_group=bklmc.ocelotsign
archives_base_name=ocelotsignmod

# Loom Properties
# bmclapi 镜像当前连接不稳定，暂时回退官方源
loom_version_manifests=https://piston-meta.mojang.com/mc/game/version_manifest_v2.json
loom_fabric_repository=https://repository.hanbings.io/proxy/
