package bklmc.ocelotsign.block;

import bklmc.ocelotsign.OcelotSignMod;
import bklmc.ocelotsign.block.custom.WallRoadSignBlock;
import bklmc.ocelotsign.item.WallRoadSignBlockItem;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.Item;
import net.minecraft.util.registry.Registry;
import net.minecraft.util.registry.Registry;
import net.minecraft.util.Identifier;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;

/**
 * 墙上道路指示牌方块注册中心
 *
 * @see bklmc.ocelotsign.block.custom.WallRoadSignBlock
 */
public class WallRoadSignBlocks {
    public static final Block BLUE_WALL_ROAD_SIGN_LEFT_TOP = registerWallRoadSignBlock("wallroadsign/blue/left_top", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_TOP = registerWallRoadSignBlock("wallroadsign/blue/top", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_RIGHT_TOP = registerWallRoadSignBlock("wallroadsign/blue/right_top", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_LEFT = registerWallRoadSignBlock("wallroadsign/blue/left", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MIDDLE = registerWallRoadSignBlock("wallroadsign/blue/middle", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_RIGHT = registerWallRoadSignBlock("wallroadsign/blue/right", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_LEFT_BOTTOM = registerWallRoadSignBlock("wallroadsign/blue/left_bottom", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_BOTTOM = registerWallRoadSignBlock("wallroadsign/blue/bottom", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_RIGHT_BOTTOM = registerWallRoadSignBlock("wallroadsign/blue/right_bottom", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_HORIZONTAL_LEFT = registerWallRoadSignBlock("wallroadsign/blue/horizontal_left", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_HORIZONTAL_MIDDLE = registerWallRoadSignBlock("wallroadsign/blue/horizontal_middle", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_HORIZONTAL_RIGHT = registerWallRoadSignBlock("wallroadsign/blue/horizontal_right", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_VERTICAL_TOP = registerWallRoadSignBlock("wallroadsign/blue/vertical_top", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_VERTICAL_MIDDLE = registerWallRoadSignBlock("wallroadsign/blue/vertical_middle", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_VERTICAL_BOTTOM = registerWallRoadSignBlock("wallroadsign/blue/vertical_bottom", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_SMALL_A = registerWallRoadSignBlock("wallroadsign/blue/small_a", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_SMALL_B = registerWallRoadSignBlock("wallroadsign/blue/small_b", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_RHOMBUS = registerWallRoadSignBlock("wallroadsign/blue/rhombus", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    public static final Block GREEN_WALL_ROAD_SIGN_LEFT_TOP = registerWallRoadSignBlock("wallroadsign/green/left_top", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_TOP = registerWallRoadSignBlock("wallroadsign/green/top", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_RIGHT_TOP = registerWallRoadSignBlock("wallroadsign/green/right_top", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_LEFT = registerWallRoadSignBlock("wallroadsign/green/left", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MIDDLE = registerWallRoadSignBlock("wallroadsign/green/middle", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_RIGHT = registerWallRoadSignBlock("wallroadsign/green/right", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_LEFT_BOTTOM = registerWallRoadSignBlock("wallroadsign/green/left_bottom", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_BOTTOM = registerWallRoadSignBlock("wallroadsign/green/bottom", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_RIGHT_BOTTOM = registerWallRoadSignBlock("wallroadsign/green/right_bottom", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_HORIZONTAL_LEFT = registerWallRoadSignBlock("wallroadsign/green/horizontal_left", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_HORIZONTAL_MIDDLE = registerWallRoadSignBlock("wallroadsign/green/horizontal_middle", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_HORIZONTAL_RIGHT = registerWallRoadSignBlock("wallroadsign/green/horizontal_right", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_VERTICAL_TOP = registerWallRoadSignBlock("wallroadsign/green/vertical_top", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_VERTICAL_MIDDLE = registerWallRoadSignBlock("wallroadsign/green/vertical_middle", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_VERTICAL_BOTTOM = registerWallRoadSignBlock("wallroadsign/green/vertical_bottom", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_SMALL_A = registerWallRoadSignBlock("wallroadsign/green/small_a", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_SMALL_B = registerWallRoadSignBlock("wallroadsign/green/small_b", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_RHOMBUS = registerWallRoadSignBlock("wallroadsign/green/rhombus", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    public static final Block YELLOW_WALL_ROAD_SIGN_LEFT_TOP = registerWallRoadSignBlock("wallroadsign/yellow/left_top", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_TOP = registerWallRoadSignBlock("wallroadsign/yellow/top", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_RIGHT_TOP = registerWallRoadSignBlock("wallroadsign/yellow/right_top", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_LEFT = registerWallRoadSignBlock("wallroadsign/yellow/left", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MIDDLE = registerWallRoadSignBlock("wallroadsign/yellow/middle", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_RIGHT = registerWallRoadSignBlock("wallroadsign/yellow/right", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_LEFT_BOTTOM = registerWallRoadSignBlock("wallroadsign/yellow/left_bottom", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_BOTTOM = registerWallRoadSignBlock("wallroadsign/yellow/bottom", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_RIGHT_BOTTOM = registerWallRoadSignBlock("wallroadsign/yellow/right_bottom", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_HORIZONTAL_LEFT = registerWallRoadSignBlock("wallroadsign/yellow/horizontal_left", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_HORIZONTAL_MIDDLE = registerWallRoadSignBlock("wallroadsign/yellow/horizontal_middle", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_HORIZONTAL_RIGHT = registerWallRoadSignBlock("wallroadsign/yellow/horizontal_right", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_VERTICAL_TOP = registerWallRoadSignBlock("wallroadsign/yellow/vertical_top", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_VERTICAL_MIDDLE = registerWallRoadSignBlock("wallroadsign/yellow/vertical_middle", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_VERTICAL_BOTTOM = registerWallRoadSignBlock("wallroadsign/yellow/vertical_bottom", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_SMALL_A = registerWallRoadSignBlock("wallroadsign/yellow/small_a", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_SMALL_B = registerWallRoadSignBlock("wallroadsign/yellow/small_b", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_RHOMBUS = registerWallRoadSignBlock("wallroadsign/yellow/rhombus", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    public static final Block WHITE_WALL_ROAD_SIGN_LEFT_TOP = registerWallRoadSignBlock("wallroadsign/white/left_top", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_TOP = registerWallRoadSignBlock("wallroadsign/white/top", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_RIGHT_TOP = registerWallRoadSignBlock("wallroadsign/white/right_top", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_LEFT = registerWallRoadSignBlock("wallroadsign/white/left", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MIDDLE = registerWallRoadSignBlock("wallroadsign/white/middle", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_RIGHT = registerWallRoadSignBlock("wallroadsign/white/right", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_LEFT_BOTTOM = registerWallRoadSignBlock("wallroadsign/white/left_bottom", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_BOTTOM = registerWallRoadSignBlock("wallroadsign/white/bottom", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_RIGHT_BOTTOM = registerWallRoadSignBlock("wallroadsign/white/right_bottom", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_HORIZONTAL_LEFT = registerWallRoadSignBlock("wallroadsign/white/horizontal_left", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_HORIZONTAL_MIDDLE = registerWallRoadSignBlock("wallroadsign/white/horizontal_middle", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_HORIZONTAL_RIGHT = registerWallRoadSignBlock("wallroadsign/white/horizontal_right", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_VERTICAL_TOP = registerWallRoadSignBlock("wallroadsign/white/vertical_top", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_VERTICAL_MIDDLE = registerWallRoadSignBlock("wallroadsign/white/vertical_middle", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_VERTICAL_BOTTOM = registerWallRoadSignBlock("wallroadsign/white/vertical_bottom", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_SMALL_A = registerWallRoadSignBlock("wallroadsign/white/small_a", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_SMALL_B = registerWallRoadSignBlock("wallroadsign/white/small_b", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_RHOMBUS = registerWallRoadSignBlock("wallroadsign/white/rhombus", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    public static final Block BROWN_WALL_ROAD_SIGN_LEFT_TOP = registerWallRoadSignBlock("wallroadsign/brown/left_top", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_TOP = registerWallRoadSignBlock("wallroadsign/brown/top", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_RIGHT_TOP = registerWallRoadSignBlock("wallroadsign/brown/right_top", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_LEFT = registerWallRoadSignBlock("wallroadsign/brown/left", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MIDDLE = registerWallRoadSignBlock("wallroadsign/brown/middle", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_RIGHT = registerWallRoadSignBlock("wallroadsign/brown/right", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_LEFT_BOTTOM = registerWallRoadSignBlock("wallroadsign/brown/left_bottom", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_BOTTOM = registerWallRoadSignBlock("wallroadsign/brown/bottom", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_RIGHT_BOTTOM = registerWallRoadSignBlock("wallroadsign/brown/right_bottom", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_HORIZONTAL_LEFT = registerWallRoadSignBlock("wallroadsign/brown/horizontal_left", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_HORIZONTAL_MIDDLE = registerWallRoadSignBlock("wallroadsign/brown/horizontal_middle", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_HORIZONTAL_RIGHT = registerWallRoadSignBlock("wallroadsign/brown/horizontal_right", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_VERTICAL_TOP = registerWallRoadSignBlock("wallroadsign/brown/vertical_top", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_VERTICAL_MIDDLE = registerWallRoadSignBlock("wallroadsign/brown/vertical_middle", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_VERTICAL_BOTTOM = registerWallRoadSignBlock("wallroadsign/brown/vertical_bottom", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_SMALL_A = registerWallRoadSignBlock("wallroadsign/brown/small_a", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_SMALL_B = registerWallRoadSignBlock("wallroadsign/brown/small_b", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_RHOMBUS = registerWallRoadSignBlock("wallroadsign/brown/rhombus", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    public static final Block ORANGE_WALL_ROAD_SIGN_LEFT_TOP = registerWallRoadSignBlock("wallroadsign/orange/left_top", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_TOP = registerWallRoadSignBlock("wallroadsign/orange/top", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_RIGHT_TOP = registerWallRoadSignBlock("wallroadsign/orange/right_top", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_LEFT = registerWallRoadSignBlock("wallroadsign/orange/left", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MIDDLE = registerWallRoadSignBlock("wallroadsign/orange/middle", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_RIGHT = registerWallRoadSignBlock("wallroadsign/orange/right", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_LEFT_BOTTOM = registerWallRoadSignBlock("wallroadsign/orange/left_bottom", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_BOTTOM = registerWallRoadSignBlock("wallroadsign/orange/bottom", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_RIGHT_BOTTOM = registerWallRoadSignBlock("wallroadsign/orange/right_bottom", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_HORIZONTAL_LEFT = registerWallRoadSignBlock("wallroadsign/orange/horizontal_left", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_HORIZONTAL_MIDDLE = registerWallRoadSignBlock("wallroadsign/orange/horizontal_middle", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_HORIZONTAL_RIGHT = registerWallRoadSignBlock("wallroadsign/orange/horizontal_right", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_VERTICAL_TOP = registerWallRoadSignBlock("wallroadsign/orange/vertical_top", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_VERTICAL_MIDDLE = registerWallRoadSignBlock("wallroadsign/orange/vertical_middle", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_VERTICAL_BOTTOM = registerWallRoadSignBlock("wallroadsign/orange/vertical_bottom", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_SMALL_A = registerWallRoadSignBlock("wallroadsign/orange/small_a", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_SMALL_B = registerWallRoadSignBlock("wallroadsign/orange/small_b", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    public static final Block NO_PARKING = registerWallRoadSignBlock("wallroadsign/extra/no_parking", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block NO_LONG_TERM_PARKING = registerWallRoadSignBlock("wallroadsign/extra/no_long_term_parking", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block FORBID_2 = registerWallRoadSignBlock("wallroadsign/extra/forbid_2", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block FORBID_3 = registerWallRoadSignBlock("wallroadsign/extra/forbid_3", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_ROUND = registerWallRoadSignBlock("wallroadsign/extra/blue_round", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block RED_ROUND = registerWallRoadSignBlock("wallroadsign/extra/red_round", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_ROUND = registerWallRoadSignBlock("wallroadsign/extra/green_round", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_ROUND = registerWallRoadSignBlock("wallroadsign/extra/yellow_round", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_ROUND = registerWallRoadSignBlock("wallroadsign/extra/white_round", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block FORBID_1 = registerWallRoadSignBlock("wallroadsign/extra/forbid_1", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block NO_ENTRY = registerWallRoadSignBlock("wallroadsign/extra/no_entry", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block HEIGHT_LIMIT = registerWallRoadSignBlock("wallroadsign/extra/height_limit", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WIDTH_LIMIT = registerWallRoadSignBlock("wallroadsign/extra/width_limit", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WEIGHT_LIMIT = registerWallRoadSignBlock("wallroadsign/extra/weight_limit", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block LIFT_SPEED_LIMIT = registerWallRoadSignBlock("wallroadsign/extra/lift_speed_limit", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block LOW_SPEED_LIMIT = registerWallRoadSignBlock("wallroadsign/extra/low_speed_limit", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block MAX_SPEED_LIMIT = registerWallRoadSignBlock("wallroadsign/extra/max_speed_limit", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WARNING = registerWallRoadSignBlock("wallroadsign/extra/warning", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WARNING_2 = registerWallRoadSignBlock("wallroadsign/extra/warning_2", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WARNING_RED_STROKE = registerWallRoadSignBlock("wallroadsign/extra/warning_red_stroke", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block STOP = registerWallRoadSignBlock("wallroadsign/extra/stop", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block NATIONAL_EXPRESSWAY = registerWallRoadSignBlock("wallroadsign/extra/national_expressway", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block PROVINCIAL_EXPRESSWAY = registerWallRoadSignBlock("wallroadsign/extra/provincial_expressway", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block NATIONAL_HIGHWAY = registerWallRoadSignBlock("wallroadsign/extra/national_highway", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block PROVINCIAL_HIGHWAY = registerWallRoadSignBlock("wallroadsign/extra/provincial_highway", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block COUNTRY_HIGHWAY = registerWallRoadSignBlock("wallroadsign/extra/country_highway", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YIELD = registerWallRoadSignBlock("wallroadsign/extra/yield", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_MILEAGE_SIGN = registerWallRoadSignBlock("wallroadsign/extra/green_mileage_sign", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_MILEAGE_SIGN = registerWallRoadSignBlock("wallroadsign/extra/blue_mileage_sign", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_HECTOMETER_SIGN = registerWallRoadSignBlock("wallroadsign/extra/green_hectometer_sign", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_HECTOMETER_SIGN = registerWallRoadSignBlock("wallroadsign/extra/blue_hectometer_sign", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    public static final Block YIELD_RED_FILL = registerWallRoadSignBlock("wallroadsign/extra/yield_red_fill", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block FORBID_4 = registerWallRoadSignBlock("wallroadsign/extra/forbid_4", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block MAX_SPEED_LIMIT_YELLOW_FILL = registerWallRoadSignBlock("wallroadsign/extra/max_speed_limit_yellow_fill", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WARNING_RED_STROKE_YELLOW_FILL = registerWallRoadSignBlock("wallroadsign/extra/warning_red_stroke_yellow_fill", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block LIFT_SPEED_LIMIT_YELLOW_FILL = registerWallRoadSignBlock("wallroadsign/extra/lift_speed_limit_yellow_fill", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WARNING_BLUE_FILL = registerWallRoadSignBlock("wallroadsign/extra/warning_blue_fill", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WARNING_YELLOW_FILL = registerWallRoadSignBlock("wallroadsign/extra/warning_yellow_fill", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WARNING_GREEN_FILL = registerWallRoadSignBlock("wallroadsign/extra/warning_green_fill", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    public static final Block BLUE_CHEVRON_ALIGNMENT_A_LEFT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/blue/a_left", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_CHEVRON_ALIGNMENT_A_RIGHT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/blue/a_right", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_CHEVRON_ALIGNMENT_B_LEFT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/blue/b_left", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_CHEVRON_ALIGNMENT_B_RIGHT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/blue/b_right", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_CHEVRON_ALIGNMENT_C_LEFT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/blue/c_left", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_CHEVRON_ALIGNMENT_C_RIGHT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/blue/c_right", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_CHEVRON_ALIGNMENT_C_UP = registerWallRoadSignBlock("wallroadsign/chevron_alignment/blue/c_up", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    public static final Block GREEN_CHEVRON_ALIGNMENT_A_LEFT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/green/a_left", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_CHEVRON_ALIGNMENT_A_RIGHT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/green/a_right", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_CHEVRON_ALIGNMENT_B_LEFT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/green/b_left", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_CHEVRON_ALIGNMENT_B_RIGHT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/green/b_right", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_CHEVRON_ALIGNMENT_C_LEFT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/green/c_left", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_CHEVRON_ALIGNMENT_C_RIGHT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/green/c_right", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_CHEVRON_ALIGNMENT_C_UP = registerWallRoadSignBlock("wallroadsign/chevron_alignment/green/c_up", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    public static final Block RED_CHEVRON_ALIGNMENT_A_LEFT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/red/a_left", new WallRoadSignBlock(Blocks.RED_CONCRETE, FabricBlockSettings.copyOf(Blocks.RED_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block RED_CHEVRON_ALIGNMENT_A_RIGHT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/red/a_right", new WallRoadSignBlock(Blocks.RED_CONCRETE, FabricBlockSettings.copyOf(Blocks.RED_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block RED_CHEVRON_ALIGNMENT_B_LEFT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/red/b_left", new WallRoadSignBlock(Blocks.RED_CONCRETE, FabricBlockSettings.copyOf(Blocks.RED_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block RED_CHEVRON_ALIGNMENT_B_RIGHT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/red/b_right", new WallRoadSignBlock(Blocks.RED_CONCRETE, FabricBlockSettings.copyOf(Blocks.RED_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block RED_CHEVRON_ALIGNMENT_C_LEFT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/red/c_left", new WallRoadSignBlock(Blocks.RED_CONCRETE, FabricBlockSettings.copyOf(Blocks.RED_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block RED_CHEVRON_ALIGNMENT_C_RIGHT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/red/c_right", new WallRoadSignBlock(Blocks.RED_CONCRETE, FabricBlockSettings.copyOf(Blocks.RED_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block RED_CHEVRON_ALIGNMENT_C_UP = registerWallRoadSignBlock("wallroadsign/chevron_alignment/red/c_up", new WallRoadSignBlock(Blocks.RED_CONCRETE, FabricBlockSettings.copyOf(Blocks.RED_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    public static final Block YELLOW_CHEVRON_ALIGNMENT_A_LEFT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/yellow/a_left", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_CHEVRON_ALIGNMENT_A_RIGHT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/yellow/a_right", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_CHEVRON_ALIGNMENT_B_LEFT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/yellow/b_left", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_CHEVRON_ALIGNMENT_B_RIGHT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/yellow/b_right", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_CHEVRON_ALIGNMENT_C_LEFT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/yellow/c_left", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_CHEVRON_ALIGNMENT_C_RIGHT = registerWallRoadSignBlock("wallroadsign/chevron_alignment/yellow/c_right", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_CHEVRON_ALIGNMENT_C_UP = registerWallRoadSignBlock("wallroadsign/chevron_alignment/yellow/c_up", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    public static final Block OVERHEAD_ROAD_EDGE_MARKER = registerWallRoadSignBlock("wallroadsign/extra/overhead_road_edge_marker", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    public static final Block BLUE_WALL_ROAD_SIGN_MINI_01 = registerWallRoadSignBlock("wallroadsign/blue/mini_01", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_02 = registerWallRoadSignBlock("wallroadsign/blue/mini_02", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_03 = registerWallRoadSignBlock("wallroadsign/blue/mini_03", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_04 = registerWallRoadSignBlock("wallroadsign/blue/mini_04", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_05 = registerWallRoadSignBlock("wallroadsign/blue/mini_05", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_06 = registerWallRoadSignBlock("wallroadsign/blue/mini_06", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_07 = registerWallRoadSignBlock("wallroadsign/blue/mini_07", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_08 = registerWallRoadSignBlock("wallroadsign/blue/mini_08", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_09 = registerWallRoadSignBlock("wallroadsign/blue/mini_09", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_10 = registerWallRoadSignBlock("wallroadsign/blue/mini_10", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_11 = registerWallRoadSignBlock("wallroadsign/blue/mini_11", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_12 = registerWallRoadSignBlock("wallroadsign/blue/mini_12", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_13 = registerWallRoadSignBlock("wallroadsign/blue/mini_13", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_14 = registerWallRoadSignBlock("wallroadsign/blue/mini_14", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_15 = registerWallRoadSignBlock("wallroadsign/blue/mini_15", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_16 = registerWallRoadSignBlock("wallroadsign/blue/mini_16", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_17 = registerWallRoadSignBlock("wallroadsign/blue/mini_17", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_18 = registerWallRoadSignBlock("wallroadsign/blue/mini_18", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BLUE_WALL_ROAD_SIGN_MINI_19 = registerWallRoadSignBlock("wallroadsign/blue/mini_19", new WallRoadSignBlock(Blocks.BLUE_CONCRETE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_01 = registerWallRoadSignBlock("wallroadsign/green/mini_01", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_02 = registerWallRoadSignBlock("wallroadsign/green/mini_02", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_03 = registerWallRoadSignBlock("wallroadsign/green/mini_03", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_04 = registerWallRoadSignBlock("wallroadsign/green/mini_04", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_05 = registerWallRoadSignBlock("wallroadsign/green/mini_05", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_06 = registerWallRoadSignBlock("wallroadsign/green/mini_06", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_07 = registerWallRoadSignBlock("wallroadsign/green/mini_07", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_08 = registerWallRoadSignBlock("wallroadsign/green/mini_08", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_09 = registerWallRoadSignBlock("wallroadsign/green/mini_09", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_10 = registerWallRoadSignBlock("wallroadsign/green/mini_10", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_11 = registerWallRoadSignBlock("wallroadsign/green/mini_11", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_12 = registerWallRoadSignBlock("wallroadsign/green/mini_12", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_13 = registerWallRoadSignBlock("wallroadsign/green/mini_13", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_14 = registerWallRoadSignBlock("wallroadsign/green/mini_14", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_15 = registerWallRoadSignBlock("wallroadsign/green/mini_15", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_16 = registerWallRoadSignBlock("wallroadsign/green/mini_16", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_17 = registerWallRoadSignBlock("wallroadsign/green/mini_17", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_18 = registerWallRoadSignBlock("wallroadsign/green/mini_18", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block GREEN_WALL_ROAD_SIGN_MINI_19 = registerWallRoadSignBlock("wallroadsign/green/mini_19", new WallRoadSignBlock(Blocks.GREEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_01 = registerWallRoadSignBlock("wallroadsign/yellow/mini_01", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_02 = registerWallRoadSignBlock("wallroadsign/yellow/mini_02", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_03 = registerWallRoadSignBlock("wallroadsign/yellow/mini_03", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_04 = registerWallRoadSignBlock("wallroadsign/yellow/mini_04", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_05 = registerWallRoadSignBlock("wallroadsign/yellow/mini_05", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_06 = registerWallRoadSignBlock("wallroadsign/yellow/mini_06", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_07 = registerWallRoadSignBlock("wallroadsign/yellow/mini_07", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_08 = registerWallRoadSignBlock("wallroadsign/yellow/mini_08", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_09 = registerWallRoadSignBlock("wallroadsign/yellow/mini_09", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_10 = registerWallRoadSignBlock("wallroadsign/yellow/mini_10", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_11 = registerWallRoadSignBlock("wallroadsign/yellow/mini_11", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_12 = registerWallRoadSignBlock("wallroadsign/yellow/mini_12", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_13 = registerWallRoadSignBlock("wallroadsign/yellow/mini_13", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_14 = registerWallRoadSignBlock("wallroadsign/yellow/mini_14", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_15 = registerWallRoadSignBlock("wallroadsign/yellow/mini_15", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_16 = registerWallRoadSignBlock("wallroadsign/yellow/mini_16", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_17 = registerWallRoadSignBlock("wallroadsign/yellow/mini_17", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_18 = registerWallRoadSignBlock("wallroadsign/yellow/mini_18", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block YELLOW_WALL_ROAD_SIGN_MINI_19 = registerWallRoadSignBlock("wallroadsign/yellow/mini_19", new WallRoadSignBlock(Blocks.YELLOW_CONCRETE, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_01 = registerWallRoadSignBlock("wallroadsign/white/mini_01", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_02 = registerWallRoadSignBlock("wallroadsign/white/mini_02", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_03 = registerWallRoadSignBlock("wallroadsign/white/mini_03", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_04 = registerWallRoadSignBlock("wallroadsign/white/mini_04", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_05 = registerWallRoadSignBlock("wallroadsign/white/mini_05", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_06 = registerWallRoadSignBlock("wallroadsign/white/mini_06", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_07 = registerWallRoadSignBlock("wallroadsign/white/mini_07", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_08 = registerWallRoadSignBlock("wallroadsign/white/mini_08", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_09 = registerWallRoadSignBlock("wallroadsign/white/mini_09", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_10 = registerWallRoadSignBlock("wallroadsign/white/mini_10", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_11 = registerWallRoadSignBlock("wallroadsign/white/mini_11", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_12 = registerWallRoadSignBlock("wallroadsign/white/mini_12", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_13 = registerWallRoadSignBlock("wallroadsign/white/mini_13", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_14 = registerWallRoadSignBlock("wallroadsign/white/mini_14", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_15 = registerWallRoadSignBlock("wallroadsign/white/mini_15", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_16 = registerWallRoadSignBlock("wallroadsign/white/mini_16", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_17 = registerWallRoadSignBlock("wallroadsign/white/mini_17", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_18 = registerWallRoadSignBlock("wallroadsign/white/mini_18", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block WHITE_WALL_ROAD_SIGN_MINI_19 = registerWallRoadSignBlock("wallroadsign/white/mini_19", new WallRoadSignBlock(Blocks.WHITE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_01 = registerWallRoadSignBlock("wallroadsign/brown/mini_01", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_02 = registerWallRoadSignBlock("wallroadsign/brown/mini_02", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_03 = registerWallRoadSignBlock("wallroadsign/brown/mini_03", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_04 = registerWallRoadSignBlock("wallroadsign/brown/mini_04", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_05 = registerWallRoadSignBlock("wallroadsign/brown/mini_05", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_06 = registerWallRoadSignBlock("wallroadsign/brown/mini_06", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_07 = registerWallRoadSignBlock("wallroadsign/brown/mini_07", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_08 = registerWallRoadSignBlock("wallroadsign/brown/mini_08", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_09 = registerWallRoadSignBlock("wallroadsign/brown/mini_09", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_10 = registerWallRoadSignBlock("wallroadsign/brown/mini_10", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_11 = registerWallRoadSignBlock("wallroadsign/brown/mini_11", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_12 = registerWallRoadSignBlock("wallroadsign/brown/mini_12", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_13 = registerWallRoadSignBlock("wallroadsign/brown/mini_13", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_14 = registerWallRoadSignBlock("wallroadsign/brown/mini_14", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_15 = registerWallRoadSignBlock("wallroadsign/brown/mini_15", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_16 = registerWallRoadSignBlock("wallroadsign/brown/mini_16", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_17 = registerWallRoadSignBlock("wallroadsign/brown/mini_17", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_18 = registerWallRoadSignBlock("wallroadsign/brown/mini_18", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block BROWN_WALL_ROAD_SIGN_MINI_19 = registerWallRoadSignBlock("wallroadsign/brown/mini_19", new WallRoadSignBlock(Blocks.BROWN_CONCRETE, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_01 = registerWallRoadSignBlock("wallroadsign/orange/mini_01", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_02 = registerWallRoadSignBlock("wallroadsign/orange/mini_02", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_03 = registerWallRoadSignBlock("wallroadsign/orange/mini_03", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_04 = registerWallRoadSignBlock("wallroadsign/orange/mini_04", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_05 = registerWallRoadSignBlock("wallroadsign/orange/mini_05", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_06 = registerWallRoadSignBlock("wallroadsign/orange/mini_06", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_07 = registerWallRoadSignBlock("wallroadsign/orange/mini_07", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_08 = registerWallRoadSignBlock("wallroadsign/orange/mini_08", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_09 = registerWallRoadSignBlock("wallroadsign/orange/mini_09", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_10 = registerWallRoadSignBlock("wallroadsign/orange/mini_10", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_11 = registerWallRoadSignBlock("wallroadsign/orange/mini_11", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_12 = registerWallRoadSignBlock("wallroadsign/orange/mini_12", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_13 = registerWallRoadSignBlock("wallroadsign/orange/mini_13", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_14 = registerWallRoadSignBlock("wallroadsign/orange/mini_14", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_15 = registerWallRoadSignBlock("wallroadsign/orange/mini_15", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_16 = registerWallRoadSignBlock("wallroadsign/orange/mini_16", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_17 = registerWallRoadSignBlock("wallroadsign/orange/mini_17", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_18 = registerWallRoadSignBlock("wallroadsign/orange/mini_18", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));
    public static final Block ORANGE_WALL_ROAD_SIGN_MINI_19 = registerWallRoadSignBlock("wallroadsign/orange/mini_19", new WallRoadSignBlock(Blocks.ORANGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).strength(0.2f,0.2f).nonOpaque()));

    /**
     * 初始化墙上道路指示牌方块注册。
     */
    public static void registerWallRoadSignBlocks() {
    }

    private static Block registerWallRoadSignBlock(String id, Block block) {
        Block registeredBlock = Registry.register(Registry.BLOCK, new Identifier(OcelotSignMod.MOD_ID, id), block);
        Registry.register(Registry.ITEM, new Identifier(OcelotSignMod.MOD_ID, id),
                new WallRoadSignBlockItem(block, new Item.Settings()));
        return registeredBlock;
    }

    /**
     * @deprecated 请使用 {@link #registerWallRoadSignBlock(String, Block)} 注册墙上道路指示牌
     */
    @Deprecated
    private static Block registerWallRoadSignBlock(String id, Block block, net.minecraft.item.Item item) {
        Block registeredBlock = Registry.register(Registry.BLOCK, new Identifier(OcelotSignMod.MOD_ID, id), block);
        registerBlockItem(id, registeredBlock, item);
        return registeredBlock;
    }

    /**
     * @deprecated 请使用 {@link #registerWallRoadSignBlock(String, Block)} 注册墙上道路指示牌
     */
    @Deprecated
    private static void registerBlockItem(String id, Block block, net.minecraft.item.Item item) {
        Registry.register(Registry.ITEM, new Identifier(OcelotSignMod.MOD_ID, id), item);
    }
}
